/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import java.sql.SQLException;
import java.util.Vector;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JPopupMenu;

import proyecto.conexionsql;
import javax.swing.table.DefaultTableModel;
import static proyecto.inteface1.result;
import javax.swing.JFrame;

/**
 *
 * @author Fanboy022
 */
public class busquedaBD extends javax.swing.JFrame {
static ResultSet result;
    /**
     * Creates new form busquedaBD
     */
     public int ultimo =0;

    public busquedaBD() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        cargarBD();
        jButton2.setEnabled(false);
        colores();
        bustext.requestFocus();
    }
        public void colores()
    {
        jButton2.setBackground(Color.white);
        jButton3.setBackground(Color.white);
        jButton4.setBackground(Color.white);
        jButton7.setBackground(Color.white);
        jButton1.setBackground(Color.white);
        bus.setBackground(Color.DARK_GRAY);
        jButton6.setBackground(Color.white);
        bus.setForeground(Color.WHITE);
    }
public void cargarBD()
    {
        DefaultTableModel model = (DefaultTableModel) tabla2.getModel();
        model.setRowCount(0);
        result = conexionsql.consulta("select*from alumno");
        
        try{
            while(result.next())
            {
                Vector c = new Vector();
                c.add(result.getInt(1));
                c.add(result.getString(2));
                c.add(result.getString(3));
                c.add(result.getString(4));
                c.add(result.getString(5));
                c.add(result.getString(6));
                model.addRow(c);
                tabla2.setModel(model);
            }
        }catch(SQLException e){
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla2 = new javax.swing.JTable();
        TITULO = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bus = new javax.swing.JButton();
        bustext = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(897, 400));
        setSize(new java.awt.Dimension(0, 0));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        tabla2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CI", "NOMBRE", "APELLIDO PATERNO", "APELLIDO MATERNO", "FECHA DE NACIMIENTO", "GENERO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla2.setToolTipText("");
        tabla2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tabla2.setDoubleBuffered(true);
        tabla2.setFillsViewportHeight(true);
        tabla2.setGridColor(new java.awt.Color(204, 204, 204));
        tabla2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabla2.getTableHeader().setReorderingAllowed(false);
        tabla2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla2);
        if (tabla2.getColumnModel().getColumnCount() > 0) {
            tabla2.getColumnModel().getColumn(0).setResizable(false);
            tabla2.getColumnModel().getColumn(1).setResizable(false);
            tabla2.getColumnModel().getColumn(2).setResizable(false);
            tabla2.getColumnModel().getColumn(3).setResizable(false);
            tabla2.getColumnModel().getColumn(4).setResizable(false);
            tabla2.getColumnModel().getColumn(5).setResizable(false);
        }

        TITULO.setBackground(new java.awt.Color(255, 255, 255));
        TITULO.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        TITULO.setForeground(new java.awt.Color(0, 102, 255));
        TITULO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TITULO.setText("BD DE ESTUDIANTES");

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        bus.setText("BUSCAR");
        bus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busActionPerformed(evt);
            }
        });

        bustext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bustextKeyReleased(evt);
            }
        });

        jButton3.setText("|>");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText(">");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setText("<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("<|");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(218, 218, 218)
                .addComponent(bustext, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bus, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bustext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bus)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));

        jButton6.setText("VOLVER");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("ACTUALIZAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setText("BORRAR");
        jButton5.setContentAreaFilled(false);
        jButton5.setOpaque(true);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(314, 314, 314))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        inteface1 h = new inteface1();
        dispose();
        h.setVisible(true);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void busActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busActionPerformed
        jButton2.setEnabled(true);
        busqueda();

    }//GEN-LAST:event_busActionPerformed
    public void busqueda()
    {
        
          if (bustext.getText().isEmpty())
       {
           JOptionPane.showMessageDialog(this, "casilla de busqueda esta vacia", "aviso",JOptionPane.ERROR_MESSAGE);
       }else{
        int busw = Integer.parseInt(bustext.getText());
        
        
        //String.valueOf(fk.getValueAt(0,0))
        DefaultTableModel model = (DefaultTableModel) tabla2.getModel();
        model.setRowCount(0);
        while (tabla2.getRowCount() > 0)
       {
           DefaultTableModel modelo = (DefaultTableModel) tabla2.getModel();
           modelo.removeRow(0);
           tabla2.setModel(modelo);
      }
        result = conexionsql.consulta("select*from alumno where ci = '"+busw+"'");
        
        try{
            while(result.next())
            {
                Vector c = new Vector();
                c.add(result.getInt(1));
                c.add(result.getString(2));
                c.add(result.getString(3));
                c.add(result.getString(4));
                c.add(result.getString(5));
                c.add(result.getString(6));
                model.addRow(c);
                tabla2.setModel(model);
            }
        }catch(SQLException e){
            
        }
        }
       if (tabla2.getRowCount() <= 0)
       {
           JOptionPane.showMessageDialog(null, "usuario no existe en la BD");
       }
            /*   if(tabla2.getRowCount() == 1)
        {
               jButton5.setBackground(Color.red);
               jButton5.setForeground(Color.white);
               jButton5.setContentAreaFilled(true);
        }*/
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       int fila = tabla2.getSelectedRow();
       int cadena;
          /*if(tabla2.getRowCount() == 1)
           {
           try {
                    cadena = JOptionPane.showConfirmDialog(this, "seguro que quieres eliminar al usuario : "+tabla2.getValueAt(0, 1).toString()+" ?","advertencia",JOptionPane.YES_NO_OPTION);
                    
                    if(cadena == JOptionPane.YES_OPTION)
                        {
                            JOptionPane.showMessageDialog(this, "usuario eliminado exitosamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                            datos.borradodedatos(Integer.parseInt(tabla2.getValueAt(0, 0).toString()));
                             cargarBD();
                        }
                    else{   
                    }
                } catch (SQLException ex) 
                {
                    
                }
           }
          else */if (tabla2.getRowCount() > 1 && tabla2.getSelectedRow() >= 0){
                   try 
                    {          
                        int tablita = tabla2.getSelectedRow();
                        cadena = JOptionPane.showConfirmDialog(this, "seguro que quieres eliminar al usuario : "+tabla2.getValueAt(tablita, 1).toString()+" ?","advertencia",JOptionPane.YES_NO_OPTION);
                        if(cadena == JOptionPane.YES_OPTION)
                        {
                         JOptionPane.showMessageDialog(this, "usuario eliminado exitosamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                         datos.borradodedatos(Integer.parseInt(tabla2.getValueAt(fila, 0).toString()));
                         cargarBD();
                        }else{
                            tabla2.clearSelection();
                            jButton5.setBackground(Color.white);
                            jButton5.setForeground(Color.black);}
                      }catch(SQLException g){}}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
                            jButton2.setEnabled(false);
                            cargarBD(); 
                            
                            bustext.setText(null);
                            jButton5.setBackground(Color.white);
                            jButton5.setForeground(Color.black);
                            jButton4.setEnabled(true);
    }//GEN-LAST:event_jButton7ActionPerformed
    public void ultimodato()
    {
         cargarBD();
      ultimo = tabla2.getRowCount()-1;
      Object v = tabla2.getValueAt(ultimo,0);
      int busw = Integer.parseInt(v.toString());
        DefaultTableModel model = (DefaultTableModel) tabla2.getModel();
        model.setRowCount(0);
        while (tabla2.getRowCount() > 0)
       {
           DefaultTableModel modelo = (DefaultTableModel) tabla2.getModel();
           modelo.removeRow(0);
           tabla2.setModel(modelo);
      }
        result = conexionsql.consulta("select*from alumno where ci = '"+busw+"'");
        
        try{
            while(result.next())
            {
                Vector c = new Vector();
                c.add(result.getInt(1));
                c.add(result.getString(2));
                c.add(result.getString(3));
                c.add(result.getString(4));
                c.add(result.getString(5));
                c.add(result.getString(6));
                model.addRow(c);
                tabla2.setModel(model);
            }
        }catch(SQLException e){     
        }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jButton2.setEnabled(true);
      ultimodato();
    }//GEN-LAST:event_jButton3ActionPerformed
    public void primerdato()
    {
         cargarBD();
        Object w = tabla2.getValueAt(0,0);
        int busw = Integer.parseInt(w.toString());
        DefaultTableModel model = (DefaultTableModel) tabla2.getModel();
        model.setRowCount(0);
        while (tabla2.getRowCount() > 0)
       {
           DefaultTableModel modelo = (DefaultTableModel) tabla2.getModel();
           modelo.removeRow(0);
           tabla2.setModel(modelo);
      }
        result = conexionsql.consulta("select*from alumno where ci = '"+busw+"'");   
        try{
            while(result.next())
            {
                Vector c = new Vector();
                c.add(result.getInt(1));
                c.add(result.getString(2));
                c.add(result.getString(3));
                c.add(result.getString(4));
                c.add(result.getString(5));
                c.add(result.getString(6));
                model.addRow(c);
                tabla2.setModel(model);
            }
        }catch(SQLException e){    
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       primerdato();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bustextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bustextKeyReleased
        
        if (evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
            busqueda();
        }
    }//GEN-LAST:event_bustextKeyReleased

    private void tabla2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla2MouseClicked

        if (tabla2.getSelectedRow() >=0)
        {
               jButton5.setBackground(Color.red);
               jButton5.setForeground(Color.white);
               jButton5.setContentAreaFilled(true);
        }
    }//GEN-LAST:event_tabla2MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         jButton2.setEnabled(true);
        DefaultTableModel fk = (DefaultTableModel) tabla2.getModel();
        String caca = String.valueOf(fk.getValueAt(0,0));
        fk.removeRow(0);
        cargarBD();
        int i = 0;
        try{
        while (tabla2.getValueAt(i,0) != caca){
            if(tabla2.getValueAt(i,0).toString().equals(caca)){
            break;
            }
            i++;
        }     

        Object v = tabla2.getValueAt(i+1,0);
        int busw = Integer.parseInt(v.toString());
        DefaultTableModel model = (DefaultTableModel) tabla2.getModel();
        model.setRowCount(0);

        while (tabla2.getRowCount() > 0){
           DefaultTableModel modelo = (DefaultTableModel) tabla2.getModel();
           modelo.removeRow(0);
           tabla2.setModel(modelo);
           
      }
        
       try{

            result = conexionsql.consulta("select*from alumno where ci = '"+busw+"'");
            while(result.next()){
                Vector c = new Vector();
                c.add(result.getInt(1));
                c.add(result.getString(2));
                c.add(result.getString(3));
                c.add(result.getString(4));
                c.add(result.getString(5));
                c.add(result.getString(6));
                model.addRow(c);
                tabla2.setModel(model);
            }
            
        }catch(SQLException e){
        }
               }catch(Exception q)
        { 
            ultimodato();
            JOptionPane.showMessageDialog(null,"no hay usuario por mostrar");
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
        DefaultTableModel fk = (DefaultTableModel) tabla2.getModel();
        String caca = String.valueOf(fk.getValueAt(0,0));
        fk.removeRow(0);
        cargarBD();
        int i = 0;
        
        try{
        while (tabla2.getValueAt(i,0) != caca){
            if(tabla2.getValueAt(i,0).toString().equals(caca)){
            break;
            }
            i++;
        }
        Object v = tabla2.getValueAt(i-1,0);
        int busw = Integer.parseInt(v.toString());
        DefaultTableModel model = (DefaultTableModel) tabla2.getModel();
        model.setRowCount(0);
        while (tabla2.getRowCount() > 0){
           DefaultTableModel modelo = (DefaultTableModel) tabla2.getModel();
           modelo.removeRow(0);
           tabla2.setModel(modelo);

      } 
        try{
            result = conexionsql.consulta("select*from alumno where ci = '"+busw+"'");
            while(result.next()){
                Vector c = new Vector();
                c.add(result.getInt(1));
                c.add(result.getString(2));
                c.add(result.getString(3));
                c.add(result.getString(4));
                c.add(result.getString(5));
                c.add(result.getString(6));
                model.addRow(c);
                tabla2.setModel(model);
            }
        }catch(SQLException e){
            
        }
        }catch(Exception q)
        {
                primerdato();
                JOptionPane.showMessageDialog(null,"no hay usuario por mostrar");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(busquedaBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(busquedaBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(busquedaBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(busquedaBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new busquedaBD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TITULO;
    private javax.swing.JButton bus;
    private javax.swing.JTextField bustext;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla2;
    // End of variables declaration//GEN-END:variables
}
